apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-app.name" . }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devops-app-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/devops-app/config"
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          envFrom:
            - secretRef:
                name: {{ include "devops-app.fullname" . }}-secret